package constant

var (
	CODE_EXIT_USER_HOME_NOT_EXIST = 15
	CODE_EXIT_PATH_NOT_ABS        = 16
	CODE_EXIT_RATE_LIMIT_INVALID  = 17
	CODE_EXIT_PORT_INVALID        = 18
	CODE_EXIT_DFGET_NOT_FOUND     = 19
	CODE_EXIT_REPO_CREATE_FAIL    = 20
	CODE_EXIT_DFGET_FAIL          = 21

	CODE_REQ_AUTH = 22
)
